/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package in.bits.blackjackdealer.ui;

import in.bits.blackjackdealer.bean.Card;
import java.util.LinkedHashSet;
import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author tarun
 */
public class DealerStats extends javax.swing.JFrame {

    /**
     * Creates new form DealerStats
     */
    public DealerStats() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        close = new javax.swing.JButton();
        TotalCardsLabel = new javax.swing.JLabel();
        DealtCardsLabel = new javax.swing.JLabel();
        RemainLabel = new javax.swing.JLabel();
        StatsHeading = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        totalCards = new javax.swing.JTextField();
        dealtCards = new javax.swing.JTextField();
        remainCards = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        statsArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        TotalCardsLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TotalCardsLabel.setText("Total Cards in Deck");

        DealtCardsLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DealtCardsLabel.setText("Total Cards Dealt");

        RemainLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        RemainLabel.setText("Total Cards Remaining");

        StatsHeading.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        StatsHeading.setText("Dealer Statistics");

        totalCards.setBackground(new java.awt.Color(51, 51, 51));
        totalCards.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        totalCards.setEnabled(false);

        dealtCards.setBackground(new java.awt.Color(51, 51, 51));
        dealtCards.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        dealtCards.setEnabled(false);

        remainCards.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        remainCards.setEnabled(false);

        statsArea.setColumns(20);
        statsArea.setRows(5);
        statsArea.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        statsArea.setEnabled(false);
        jScrollPane1.setViewportView(statsArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(RemainLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TotalCardsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DealtCardsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(remainCards, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(dealtCards, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                .addComponent(totalCards, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addGap(94, 94, 94))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(StatsHeading))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(StatsHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalCardsLabel)
                    .addComponent(totalCards, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DealtCardsLabel)
                    .addComponent(dealtCards, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RemainLabel)
                    .addComponent(remainCards, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        int in = JOptionPane.showConfirmDialog(this,"Are You Sure?", "Are You Sure?", JOptionPane.YES_NO_OPTION);
        
        if(in == JOptionPane.YES_OPTION){
            this.dispose();
        }
    }//GEN-LAST:event_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public void setTotalCards(int total){
        totalCards.setText(""+total);
    }
    
    public void setDealtCards(int dealt){
        dealtCards.setText(""+dealt);
    }
    
    public void setRemainingCards(int remaining){
        remainCards.setText(""+remaining);
    }
    
    public void setStats(LinkedList<Card> deck){
        String hearts = "HEARTS :\t";
        String spades = "SPADES :\t";
        String diamonds = "DIAMONDS:\t";
        String clubs = "CLUBS:\t";
        System.out.println("Cards------------------------->");
        System.out.println(deck);
        for(Card card: deck){
            switch(card.getSuit().getSuitName()){
                case "HEARTS": hearts+=card.getCardNumber()+",";
                    break;
                case "SPADES": spades+=card.getCardNumber()+",";
                    break;
                case "DIAMONDS": diamonds+=card.getCardNumber()+",";
                    break;
                case "CLUBS": clubs+=card.getCardNumber()+",";
                    break;
                default:
            }
            statsArea.setText(hearts.substring(0, hearts.length()-1)+"\n"+spades.substring(0, spades.length()-1)+"\n"+diamonds.substring(0, diamonds.length()-1)+"\n"+clubs.substring(0, clubs.length()-1));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DealtCardsLabel;
    private javax.swing.JLabel RemainLabel;
    private javax.swing.JLabel StatsHeading;
    private javax.swing.JLabel TotalCardsLabel;
    private javax.swing.JButton close;
    private javax.swing.JTextField dealtCards;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField remainCards;
    private javax.swing.JTextArea statsArea;
    private javax.swing.JTextField totalCards;
    // End of variables declaration//GEN-END:variables
}
